[core]
reloadable = true
order = 0

[package]
version = "0.4.3"
category = "Simulation"
title = "Isaac Sim Synthetic Data Utilities"
description = "Utility functions for generating synthetic data"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "synthetic", "utils"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"omni.kit.uiapp" = {}
"omni.syntheticdata" = {}
"omni.kit.pip_archive" = {} # pulls in pillow
"omni.isaac.core" = {}
"omni.isaac.core_archive" = {}

[[python.module]]
name = "omni.isaac.synthetic_utils"

[[python.module]]
name = "omni.isaac.synthetic_utils.tests"

[[test]]

dependencies = [
    "omni.hydra.rtx",                       # "omni.hydra.pxr", Can we run and pass with Storm ?
    "omni.kit.viewport.utility",
    "omni.kit.viewport.window",
    "omni.physx",
    "omni.kit.primitive.mesh",
    "omni.kit.material.library",
]