[core]
reloadable = true
order = 0

[package]
# Loads models from: https://shapenet.org/
version = "2.0.1"
title = "Isaac Shapenet"
category = "Isaac"
description="An extension that allows you to load shapenet models into the scene from a local database"
authors = ["NVIDIA"]
keywords = ["kit", "shapenet", "data"]
changelog = "docs/CHANGELOG.md"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"omni.kit.uiapp" = {}
"omni.kit.asset_converter" = {}
"omni.kit.commands" = {}
"omni.kit.menu.utils" = {}
"omni.kit.widget.settings" = {}
"omni.physx" = {}
"omni.isaac.ui" = {}

[[python.module]]
name = "omni.isaac.shapenet"

[python.pipapi]
requirements = ["certifi==2021.5.30"]
use_online_index = true

[[test]]
args = ["--/exts/omni.kit.renderer.core/compatibilityMode=true"]