[core]
reloadable = true
order = 0

[package]
version = "0.1.1"
title = "Isaac Sim Synthetic Data Recorder"
description = "Tool to record synthetic data"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "synthetic", "recorder"]
changelog = "docs/CHANGELOG.md"
category = "Simulation"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"omni.syntheticdata" = {}
"omni.isaac.synthetic_utils" = {}

[[python.module]]
name = "omni.isaac.synthetic_recorder"
