# GENERAL NOTE the paths need to be ABSOLUTE!
env_path: "/ps/project/irotate/3DFRONT/USD-exports"
use_stl: True # this disable stl loading thus placement AND initial robot heading
use_npy: True # use limits of the environment saved in the npy file located in the same folder of the environment
meters_per_unit: 0.01
human_path: "/ps/project/irotate/cloth3d/exported_usd/"
base_env_path: "/media/ebonetto/WindowsData/ov/isaac_sim-2022.2.1/GRADE-RR/usds/env_base.usd"
reload_references: False
generate_map: True
clean_base_env: False
only_placement: False
robot_mesh_path: "/media/ebonetto/WindowsData/ov/isaac_sim-2022.2.1/GRADE-RR/meshes/drone.dae"
usd_robot_path: "/media/ebonetto/WindowsData/ov/isaac_sim-2022.2.1/GRADE-RR/usds/drone_2022.usd"
out_folder: "/media/ebonetto/WindowsData/exp_out2/"
out_folder_npy: "/media/ebonetto/WindowsData/exp_out2/"
fps: 30
num_robots: 1
num_humans: 40
max_distance_human_ground: 0.1 # max distance from human to ground to be consider to force the first frame grounding of animations
allow_collision: 200
experiment_length: 1800 # camera frames length
autonomous: True # true -> FUEL, false -> random goals
obstacles: {
  "shapenet": 0, # 5, 10
  "google": 1
}
physics_hz: 240 # NOTE THAT THIS IS THE RATE OF CLOCK AND IMU
render_hz: 240 # LEAVE IT EQUAL TO PHYSICS HZ
ratio_tf: 2 # physics_hz/ratio_tf = tf publish hz
ratio_odom: 4 # physics_hz/ratio_odom = odom publish hz
ratio_camera: 8 # physics_hz/ratio_cam = imgs publish hz
bootstrap_exploration: 1 # seconds to boostrap exploration (min(abs(this_value), 1/(physics_hz/ratio_camera))
reverse_strategy: "avg" # in [min, max, avg, half, none], works only with animated sequences
robot_sensor_size: [ 640, 480 ]
npy_sensor_size: [ 1920, 1080]
_random_light: { "intensity": True,
                 "color": True,
                 "intensity_interval": [ 600, 4500 ], # [min, max], for rtx
                 "during_experiment": False,
                 "n-frames": 24,
                 "smooth": False }
_random_roughness: {
  "enabled": True,
  "intensity_interval": [ 0.1, 0.9 ]
}
env_prim_path: "/World/home"
robot_base_prim_path: "/my_robot_"
human_base_prim_path: "/my_human_"
max_human_anim_len: 500 # max human anim length to be considered in frames
min_human_anim_len: 50 # min human anim length to be loaded in frames
_recorder_settings: {
  "rgb": { "enabled": True },
  "depth": { "enabled": False, "colorize": False, "npy": True },
  "depthLinear": { "enabled": True, "colorize": False, "npy": True },
  "instance": { "enabled": True, "colorize": False, "npy": True, "mappings": True },
  "semantic": { "enabled": False, "colorize": False, "npy": True, "mappings": True },
  "bbox_2d_tight": { "enabled": True, "colorize": False, "npy": True },
  "bbox_2d_loose": { "enabled": True, "colorize": False, "npy": True },
  "normals": { "enabled": False, "colorize": False, "npy": True },
  "motion-vector": { "enabled": False, "colorize": True, "npy": True },
  "bbox_3d": { "enabled": True, "colorize": False, "npy": True },
  "camera": { "enabled": True, "colorize": True, "npy": True },
  "poses": { "enabled": True, "colorize": True, "npy": True },
}
google_obj_folder: "/ps/project/irotate/google_scanned_objects"
google_obj_shortlist: ""
shapenet_local_dir: "/ps/project/irotate/ShapeNet"
shapenet_username: ""
shapenet_password: ""
synsetId: "random"
modelId: "random"
is_iRotate: False
